# -*- coding: utf-8 -*-
"""gold-portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnKnO62a-xG15uhleNbg1amdfZlfdVMj
"""

# 1. Authenticate
from google.colab import auth
auth.authenticate_user()
print('Authenticated Successfully')

# 2. Import Libraries
from google.cloud import bigquery
import pandas as pd
import numpy as np

# 3. Initialize the client
project_id = 'pp26-488519'
client = bigquery.Client(project=project_id)

# 4. Pull the data
sql = """
SELECT * FROM `pp26-488519.gld_price.v_gold_risk_analysis`
ORDER BY Market_Date ASC
"""

df = client.query(sql).to_dataframe()
df['Market_Date'] = pd.to_datetime(df['Market_Date'])
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Plotting Setup ---
sns.set_theme(style="whitegrid")
fig, ax1 = plt.subplots(figsize=(14, 7))

# --- 2. Plotting Gold Volatility (The Risk Signal from GBQ) ---
color_vol = '#E67E22' # Deep Orange
ax1.set_xlabel('Timeline', fontsize=12)
ax1.set_ylabel('Gold 30d Volatility', color=color_vol, fontsize=12, fontweight='bold')
sns.lineplot(data=df, x='Market_Date', y='Gold_30d_Vol', color=color_vol, ax=ax1, linewidth=2, label='Gold Volatility')
ax1.tick_params(axis='y', labelcolor=color_vol)

# --- 3. Plotting S&P 500 (The Market Benchmark) ---
ax2 = ax1.twinx()
color_spx = '#2E5A88' # Professional Blue
ax2.set_ylabel('S&P 500 Index', color=color_spx, fontsize=12, fontweight='bold')
sns.lineplot(data=df, x='Market_Date', y='Sp500_index', color=color_spx, ax=ax2, alpha=0.3, label='S&P 500')
ax2.tick_params(axis='y', labelcolor=color_spx)

# --- 4. Highlighting Equity Stress Periods ---
# Shading areas where GBQ flagged 'Equity Stress'
stress_dates = df[df['Market_Regime'] == 'Equity Stress']['Market_Date']
for date in stress_dates:
    ax1.axvspan(date, date + pd.Timedelta(days=1), color='red', alpha=0.08)

# --- 5. Finishing Touches ---
plt.title('Gold Volatility vs. Equity Market Stress (Risk Transmission Analysis)', fontsize=16, pad=20)
fig.tight_layout()
plt.savefig('gold_vs_spx_risk_analysis.png', dpi=300)
plt.show()

# --- 6. STATISTICAL ANALYSIS & SUMMARY TABLE ---
# Correlation using GBQ engineered columns
correlation = df['Gold_Log_Return'].corr(df['SPX_Log_Return'])

print("-" * 60)
print(f"OVERALL CORRELATION (Gold vs S&P 500): {correlation:.4f}")
print("-" * 60)

# Regime Performance Summary
regime_stats = df.groupby('Market_Regime').agg({
    'Gold_Log_Return': ['count', 'mean', 'std'],
    'SPX_Log_Return': ['mean']
}).reset_index()

# Flattening multi-index columns for readability
regime_stats.columns = ['Regime', 'Day_Count', 'Avg_Gold_Ret', 'Gold_Risk_Std', 'Avg_SPX_Ret']

print("REGIME PERFORMANCE SUMMARY (Based on GBQ Regimes)")
print(regime_stats.to_string(index=False))
print("-" * 60)

# Logic Check: Hedge Behavior Insight
hedge_days = len(df[df['Market_Regime'] == 'Hedge Behavior'])
print(f"Insight: Gold acted as a Safe Haven on {hedge_days} specific days.")